Repository cernopendata/opendata.cern.ch, pull requests merged in 2018-03, with the labels that each got.

#2350 CMS: update github links in sw records
  cernopendata/modules/fixtures/data/records/cms-validation-code-Run2010B.json
Labels: Experiment: CMS, Status: in review, Topic: records

#2353 fixtures: remove additional text in description
  cernopendata/modules/fixtures/data/records/cms-raw-datasets-Run2011A.json
  cernopendata/templates/cernopendata_records_ui/records/record_detail.html
Labels: Status: in review

#2354 records: Split configuration files
  cernopendata/modules/fixtures/data/records/cms-configuration-files-2012.json
  cernopendata/modules/fixtures/data/records/cms-configuration-files-Run2011A.json
Labels: Status: in review

#2355 templates: display pile-up information
  cernopendata/modules/fixtures/data/records/cms-simulated-datasets-Run2011A.json
  cernopendata/templates/cernopendata_records_ui/records/record_detail.html
Labels: Status: in review

#2358 CMS: small update in 2011 getting started
  cernopendata/modules/fixtures/data/docs/cms-getting-started-2011/cms-getting-started-2011.md
Labels: Experiment: CMS, Status: in review, Topic: docs

#2359 Update cms-virtual-machine-2010.md
  cernopendata/modules/fixtures/data/docs/cms-getting-started-2010/cms-getting-started-2010.md
  cernopendata/modules/fixtures/data/docs/cms-guide-for-conddb/cms-guide-for-conddb.md
  cernopendata/modules/fixtures/data/docs/cms-virtual-machine-2010/cms-virtual-machine-2010.md
Labels: Status: in review

#2360 docs: add related field for docs
  cernopendata/jsonschemas/records/docs-v1.0.0.json
  cernopendata/modules/fixtures/data/docs/cms-physics-objects-2010/cms-physics-objects-2010.json
  cernopendata/modules/fixtures/data/docs/cms-physics-objects-2011/cms-physics-objects-2011.json
  cernopendata/modules/pages/views.py
  cernopendata/modules/theme/static/scss/styles.scss
  cernopendata/modules/theme/views.py
  cernopendata/templates/cernopendata_records_ui/docs/detail.html
Labels: Status: in review

#2361 records: updates cms-tools-vm-image
  cernopendata/modules/fixtures/data/records/cms-tools-vm-image.json
Labels: Status: in review

#2362 templates: fix old links
  cernopendata/modules/pages/views.py
Labels: Status: in review

#2363 pages: add vm/validation/report link
  cernopendata/modules/pages/views.py
Labels: Status: in review

#2365 records: CMS 2011 simulates datasets rich index files
  cernopendata/modules/fixtures/data/records/cms-simulated-datasets-Run2011A.json
Labels: Experiment: CMS, Status: in review, Topic: files, Topic: records

#2366 global: removal of trailing whitespace
  cernopendata/modules/fixtures/data/records/cms-configuration-files-2012.json
  cernopendata/modules/fixtures/data/records/cms-configuration-files-Run2011A.json
  cernopendata/static/templates/cernopendata_search_ui/facets.html
  cernopendata/templates/cernopendata/search.html
  cernopendata/templates/cernopendata_records_ui/default_export.html
  cernopendata/templates/cernopendata_records_ui/terms/detail.html
  run-tests.sh
Labels: Status: in review, Topic: records, Topic: templates

#2367 logging: add support for logging to Sentry
  MANIFEST.in
  cernopendata/config.py
  docker-compose-dev.yml
  docker-compose.yml
  requirements-production.txt
  sentry/Dockerfile
  sentry/config.yml
  sentry/docker-entrypoint.sh
  sentry/initialize.json
  sentry/initialize.py
  sentry/sentry.conf.py
  setup.py
Labels: Status: in review
