Repository cernopendata/opendata.cern.ch, pull requests merged in 2018-12, with the labels that each got.

#2458 Glossary: more terms
  cernopendata/modules/fixtures/data/terms/terms.json
Labels: Status: in review

#2457 docs: categorisation of MC datasets
  cernopendata/modules/fixtures/data/docs/simulated-dataset-categories/simulated-dataset-categories.json
  cernopendata/modules/fixtures/data/docs/simulated-dataset-categories/simulated-dataset-categories.md
Labels: Status: in review

#2455 docs: improve cms-mc-production-overview
  cernopendata/modules/fixtures/data/docs/cms-mc-production-overview/cms-mc-production-overview.md
Labels: Status: in review

#2464 Fixes typo in the description of record 1802
  cernopendata/modules/fixtures/data/records/cms-condition-data-2012.json
  cernopendata/modules/fixtures/data/records/cms-condition-data-Run2011A.json
Labels: Status: in review

#2471 Installation: bump markdown engines version.
  DEVELOPING.rst
  cernopendata/modules/fixtures/data/docs/cms-guide-for-education/cms-guide-for-education.md
  cernopendata/modules/markdown/ext.py
  requirements-production.txt
Labels: Status: in review

#2473 global: removal of unused types
  cernopendata/config.py
  cernopendata/jsonschemas/records/data-policies-v1.0.0.json
  cernopendata/jsonschemas/records/datasets-v1.0.0.json
  cernopendata/jsonschemas/records/software-v1.0.0.json
  cernopendata/mappings/records/data-policies-v1.0.0.json
  cernopendata/mappings/records/datasets-v1.0.0.json
  cernopendata/mappings/records/software-v1.0.0.json
  cernopendata/modules/fixtures/cli.py
  cernopendata/modules/fixtures/data/data-policies-v1.0.0.json
  cernopendata/modules/records/fetchers/datasetid.py
  cernopendata/modules/records/fetchers/softid.py
  cernopendata/modules/records/minters/datasetid.py
  cernopendata/modules/records/minters/softid.py
  cernopendata/modules/records/providers/datasetid.py
  cernopendata/modules/records/providers/softid.py
  cernopendata/static/templates/search/briefs/dataset.html
  cernopendata/static/templates/search/briefs/software.html
  cernopendata/templates/cernopendata_records_ui/records/dataset_detail.html
  cernopendata/templates/cernopendata_records_ui/records/software_detail.html
  setup.py
Labels: Status: in review

#2479 records: topic becomes categories
  cernopendata/config.py
  cernopendata/jsonschemas/records/record-v1.0.0.json
  cernopendata/mappings/records/record-v1.0.0.json
  cernopendata/modules/fixtures/data/records/cms-simulated-datasets-Run2011A.json
  cernopendata/templates/cernopendata/search.html
Labels: Status: in review

#2483 glosary:
  cernopendata/modules/fixtures/data/terms/terms.json
Labels: Status: in review

#2480 records: CMS 2012 MC dataset categories
  cernopendata/modules/fixtures/data/records/cms-simulated-datasets-2012.json
  cernopendata/modules/fixtures/data/records/cms-simulated-datasets-Run2011A.json
Labels: Status: in review

#2478 records: cms mc 2011 new dataset
  cernopendata/modules/fixtures/data/records/cms-simulated-datasets-Run2011A.json
Labels: Status: in review

#2484 installation: requests and marshmallow updates
  requirements-production.txt
  setup.py
Labels: Status: in review

#2485 installation: Flask upgrade
  cernopendata/modules/fixtures/cli.py
  requirements-production.txt
  scripts/populate-instance.sh
  setup.py
Labels: Status: in review

#2486 record-template: changes to improve readability
  cernopendata/templates/cernopendata_records_ui/records/record_detail.html
Labels: Status: in review

#2488 glossary: fix "see also" terms
  cernopendata/modules/fixtures/data/terms/terms.json
Labels: Status: in review

#2491 Create cms-pileup-datasets-2011.json
  cernopendata/modules/fixtures/data/records/cms-pileup-datasets-2011.json
  cernopendata/templates/cernopendata_records_ui/records/record_detail.html
Labels: CMS: MC generation, Experiment: CMS, Status: in review, Topic: records

#2493 records: add CMS MC 2010
  cernopendata/modules/fixtures/data/records/cms-simulated-datasets-2010.json
Labels: Status: in review

#2495 templates: category and subcategory badges
  cernopendata/modules/theme/static/scss/styles.scss
  cernopendata/static/templates/search/briefs/record.html
  cernopendata/templates/cernopendata_records_ui/records/record_detail.html
Labels: Status: in review

#2500 templates: conditional display of category badges
  cernopendata/templates/cernopendata_records_ui/records/record_detail.html
Labels: Status: in review

#2496 scripts: drop DB option in clean-instance.sh
  scripts/clean-instance.sh
Labels: Status: in review

#2503 Add new GTs to condition data documentation
  cernopendata/modules/fixtures/data/docs/cms-guide-for-conddb/cms-guide-for-conddb.md
Labels: CMS: Global tag, CMS: instructions, Experiment: CMS, Status: in review, Topic: docs
