Repository cernopendata/opendata.cern.ch, pull requests merged in 2019-03, with the labels that each got.

#2521 records: CMS validation software file size fix
  cernopendata/modules/fixtures/data/records/cms-validation-code-Run2010B.json
Labels: Experiment: CMS, Lane: fast, Status: in review, Topic: files, Topic: records

#2522 recrods: fix records 5500 and 5501
  cernopendata/modules/fixtures/data/records/cms-tools-higgsexample20112012.json
Labels: Status: in review

#2527 records: example of methodology.steps fixtures
  cernopendata/modules/fixtures/data/records/cms-simulated-datasets-2012.json
Labels: Status: in review

#2530 models: add generation steps within methodology
  cernopendata/jsonschemas/records/record-v1.0.0.json
Labels: Status: in review

#2481 add explanation about the HLT path definition
  cernopendata/modules/fixtures/data/docs/cms-guide-trigger-system/cms-guide-trigger-system.md
Labels: CMS: instructions, CMS: trigger, Experiment: CMS, Status: in review

#2539 records: add Run2 machine learning samples
  cernopendata/modules/fixtures/data/records/cms-simulated-datasets-Run2-datascience.json
Labels: Status: in review

#2534 records: ALICE file sizes and checksums
  cernopendata/modules/fixtures/data/records/alice-analysis-modules.json
  cernopendata/modules/fixtures/data/records/alice-learning-resources.json
Labels: Status: in review
