Repository cernopendata/opendata.cern.ch, pull requests merged in 2019-04, with the labels that each got.

#2546 fixtures: amend methodology steps
  cernopendata/modules/fixtures/data/records/cms-simulated-datasets-2012.json
Labels: Status: in review

#2545 records: adds filePreviewer for methodologies
  cernopendata/modules/theme/bundles.py
  cernopendata/modules/theme/static/scss/styles.scss
  cernopendata/static/templates/filePreviewModal.html
  cernopendata/templates/cernopendata_records_ui/records/detail.html
  cernopendata/templates/cernopendata_records_ui/records/record_detail.html
  cernopendata/templates/cernopendata_theme/page.html
  setup.py
Labels: Need: work, Status: in review

#2547 records: enrich record schema
  cernopendata/jsonschemas/records/record-v1.0.0.json
Labels: Status: in review

#2548 records: CMS MC 2012 methodology steps fix
  cernopendata/modules/fixtures/data/records/cms-simulated-datasets-2012.json
Labels: Status: in review

#2551 ui: fix for missing 'recid' field in conffiles
  cernopendata/templates/cernopendata_records_ui/records/record_detail.html
Labels: Status: in review

#2554 records: CMS Run2 datascience methodology steps fix
  cernopendata/modules/fixtures/data/records/cms-simulated-datasets-Run2-datascience.json
Labels: Experiment: CMS, Status: in review, Topic: records

#2557 records: display full configuration files titles
  cernopendata/modules/fixtures/data/records/cms-simulated-datasets-2012.json
  cernopendata/modules/fixtures/data/records/cms-simulated-datasets-Run2-datascience.json
Labels: Status: in review

#2558 search: fixes facet sidebar for long names
  cernopendata/modules/theme/static/scss/styles.scss
  cernopendata/static/templates/cernopendata_search_ui/facets.html
  cernopendata/templates/cernopendata/search.html
Labels: Status: in review

#2564 ui: file preview modal "copy to clipboard" button
  cernopendata/modules/theme/bundles.py
  cernopendata/modules/theme/static/scss/styles.scss
  cernopendata/static/templates/filePreviewModal.html
  cernopendata/templates/cernopendata_records_ui/records/detail.html
Labels: Status: in review

#2567 records: add an example ondemand 2012 MC
  cernopendata/jsonschemas/records/record-v1.0.0.json
  cernopendata/modules/fixtures/data/records/cms-simulated-datasets-2012.json
Labels: Status: in review

#2568 records: codemirror - ablility to copy selected text
  cernopendata/static/templates/filePreviewModal.html
  cernopendata/templates/cernopendata_records_ui/records/detail.html
Labels: Status: in review

#2565 records: parse description into steps
  cernopendata/modules/fixtures/data/records/cms-simulated-datasets-Run2011A.json
  cernopendata/templates/cernopendata_records_ui/records/record_detail.html
Labels: Status: in review

#2569 templates: add disclaimer for "ondemand" records
  cernopendata/modules/theme/static/scss/styles.scss
  cernopendata/templates/cernopendata_records_ui/records/record_detail.html
Labels: Status: in review

#2550 records: add data science jettuples
  cernopendata/modules/fixtures/data/records/cms-derived-Run2-datascience.json
Labels: Need: information, Need: work, Status: in review

#2573 templates: display of dataset semantic types
  cernopendata/templates/cernopendata_records_ui/records/record_detail.html
Labels: Status: in review, Topic: templates

#2580 templates: add tabular semantic display
  cernopendata/templates/cernopendata_records_ui/records/record_detail.html
Labels: Status: in review

#2583 templates: display keywords badges
  cernopendata/modules/theme/static/scss/styles.scss
  cernopendata/templates/cernopendata_records_ui/records/record_detail.html
Labels: Status: in review

#2579 records: amend Run2 datascience abstract description
  cernopendata/modules/fixtures/data/records/cms-simulated-datasets-Run2-datascience.json
Labels: Status: in review

#2587 search: filter away on-demand datasets
  cernopendata/config.py
  cernopendata/mappings/records/record-v1.0.0.json
  cernopendata/modules/records/search/facets.py
  cernopendata/modules/records/search/query.py
  cernopendata/static/templates/cernopendata_search_ui/facets.html
Labels: Status: in review

#2582 records: fixes for record 12100
  cernopendata/modules/fixtures/data/records/cms-derived-Run2-datascience.json
Labels: Need: information, Status: in review

#2595 Adds Run2010A records
  cernopendata/modules/fixtures/data/records/cms-primary-datasets.json
Labels: CMS: primary datasets, Experiment: CMS, Status: in review, Topic: records

#2594 records: add methodology steps for 2010 simulated
  cernopendata/modules/fixtures/data/records/cms-simulated-datasets-2010.json
Labels: Status: in review
